spring:
  application:
    name: eureka-service-one
server:
  port: 8001
eureka:
  instance:
    instance-id: 127.0.0.1:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # Eureka 服务中心
      defaultZone: http://127.0.0.1:8000/eureka/